### ISSUE TITLE
Does not work for arXiv doi

### ISSUE THREAD

**Issue by zcysxy** [not-a-feature/citation-badge#1]
Thanks for this tool! Seems like it does not support arXiv doi, such as <https://doi.org/10.48550/arXiv.2201.02177>. The number of citations is constantly zero.

**Comment by not-a-feature** [comment]
Hi!

Thank you for the feedback.
I'm going to investigate this case as other DOIs seem to work.

**Comment by not-a-feature** [comment]
Seems to be fixed: [![Citation Badge](https://api.juleskreuer.eu/citation-badge.php?doi=10.48550/arXiv.2201.02177)](https://juleskreuer.eu/projekte/citation-badge/)

The logs indicate a caching error that prevented the citation count from updating. This seems to be caused by an incorrect default 'last update' timestamp. The timestamp error likely occurred when I recently switched the database backend, causing a change in the default timestamp value.

If this issue is resolved, feel free to close it. :)

**Comment by zcysxy** [comment]
Thanks for the swift response! I don't know why it still does not work for relatively newer papers, for example, `10.48550/arXiv.2401.15273`. I have waited for more than 24 hrs.

**Comment by not-a-feature** [comment]
Seems to work for me: [![Citation Badge](https://api.juleskreuer.eu/citation-badge.php?doi=10.48550/arXiv.2401.15273)](https://juleskreuer.eu/projekte/citation-badge/)

I don't get any errors and it seems to be just a caching issue on your side. If you are using the badge on GitHub, the badge is cached (by github, i have no control over this) sometime for a week.

**Comment by zcysxy** [comment]
Yeah it indeed is a cache issue on my end 😵
